### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by PiyalGeorge** [lewes6369/TensorRT-Yolov3#1]
Does this repo with yolov3 works at real-time fps(30 fps)?

**Comment by lewes6369** [comment]
Hi,@PiyalGeorge. It depends on gpu device and yolov3 model.

See the result below.(The model tested are all official)

Model | GPU | Mode | Inference Time
-- | -- | -- | -- 
Yolov3-608 | GTX 1060 | float32 | 48.599ms
Yolov3-416 |  GTX 1060 | float32 | 24.177ms
Yolov3-608 | GTX 1080 Ti | float32 | 19.353ms
Yolov3-608 | GTX 1080 Ti | int8 | 9.727ms
Yolov3-416 |  GTX 1080 Ti | float32 | 9.677ms
Yolov3-416 |  GTX 1080 Ti | int8 | 6.129ms  | li

PS: the yolo layer time are not included, I implemented the layer on cpu at present . It may cost 1~2ms depending on your cpu.

**Comment by PiyalGeorge** [comment]
@lewes6369 , Great Thanks. Thanks a lot. Hoping you will be able to complete this repo fast.
