### ISSUE TITLE
Message type "ditcaffe.LayerParameter" has no field named "upsample_param".

### ISSUE THREAD

**Issue by noending** [lewes6369/TensorRT-Yolov3#10]
Hi there, when I was trying run this demo, error info was like which I paste below
""""
####### end args####### 
init plugin proto: ./yolov3_608.prototxt caffemodel: ./yolov3_608.caffemodel
Begin parsing model...
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param".
ERROR: CaffeParser: Could not parse deploy file
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)
""""

I saw the tensorrtWrapper has the upsamleLayer,  and I've no idea how to solve this issue

**Comment by VigorPoppy** [comment]
#2 
check it

**Comment by GodoLucifer** [comment]
I met this error, to annotate the parameter "upsample_param" in prototxt file at line 2622 and 2932 , like this :

layer {
    bottom: "layer85-conv"
    top: "layer86-upsample"
    name: "layer86-upsample"
    type: "Upsample"
    #upsample_param {
    #    scale: 2
    #}
}

layer {
    bottom: "layer97-conv"
    top: "layer98-upsample"
    name: "layer98-upsample"
    type: "Upsample"
    #upsample_param {
    #    scale: 2
    #}
}

**Comment by fengzifrank** [comment]
me too 
 Error parsing text-format ditcaffe.NetParameter: 2622:20: Message type "ditcaffe.LayerParameter" has no field named "upsample_param".
ERROR: CaffeParser: Could not parse deploy file
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)
root@0209cc544198:/opt/tensorrt/Tens

how  to  do?
