### ISSUE TITLE
error while executing in int8 mode

### ISSUE THREAD

**Issue by shiva13425** [lewes6369/TensorRT-Yolov3#13]
While executing:
./install/runYolov3 --caffemodel=./yolov3_416.caffemodel --prototxt=./yolov3_416.prototxt --input=./test.jpg --W=416 --H=416 --class=80 --mode=int8 --calib=./calib_sample.txt

ERROR:
load batch 0 to 0
load batch 1 to 1
**runYolov3: NvPluginYOLO.cu:58: virtual void nvinfer1::plugin::PReLU::configure(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, int): Assertion `mBatchDim == 1' failed.**

Kindly share your comments. Thanks

**Comment by lewes6369** [comment]
Just run one more time, using the cache it will be OK. 
I thought that is a bug in PReLU by tensorRT implement. Testing other models is OK once.

**Comment by shiva13425** [comment]
@lewes6369 Thanks . It worked.

**Comment by haithink** [comment]
yes, run the program with the same arguments and there will be no error.
