### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by shiva13425** [lewes6369/TensorRT-Yolov3#14]
@lewes6369 currently I have modified tensorRT version and while compiling am getting the below error,

PluginFactory.h:56:141: error: invalid new-expression of abstract class type ‘nvinfer1::UpsampleLayerPlugin’
 UpsampleLayerPlugin>(new UpsampleLayerPlugin(UPSAMPLE_SCALE,CUDA_THREAD_NUM)));
                                                                            ^
compilation terminated due to -Wfatal-errors.
Note : am using TensorRT5
Its working in TensorRT4.

Kindly share your comments.

**Comment by lewes6369** [comment]
What is your TensorRT version ? Do you used the IPluginV2 ?

I have tested in TensorRT 5.0.2.6 , it is still compatible with the pluginFactory and the IPlugin. if you used the IPluginV2 , you need to override some new virtual funcs and add the IPluginCreator.

**Comment by shiva13425** [comment]
@lewes6369 am currently using TensorRT 5.0.0.10. I will try with TensorRT 5.0.2.6.
Thanks .

**Comment by shiva13425** [comment]
Thanks @lewes6369 . The issue was fixed with TensorRT 5.0.2.6.
