### ISSUE TITLE
How to load TRTEngine instead of building and saving again?

### ISSUE THREAD

**Issue by JPPunk** [lewes6369/TensorRT-Yolov3#15]
Great work! I'm new to TRT, this helped me a lot. But how can I use the engine which is already saved, instead of letting it build and save the engine every time? Thanks.

**Comment by lewes6369** [comment]
Hi,@JPPunk ,just uncomment the line " //#define LOAD_FROM_ENGINE" in main.cpp , or add_definitions(-DLOAD_FROM_ENGINE) in CMakeLists.txt. Then rebuild and run the program.

Notice: If you modify the caffemodel or the prototxt, it should generate the engine again.
