### ISSUE TITLE
runtime error when parsing caffemodel

### ISSUE THREAD

**Issue by bigyaofei** [lewes6369/TensorRT-Yolov3#19]
I have build program successfully, but when run the demo, it occurs an error when parsing caffemodel.
![screenshot from 2019-02-13 16-34-53](https://user-images.githubusercontent.com/30283150/52698042-abd19e80-2fad-11e9-9ca6-b04ab7d02161.png)
The yolov3 prototxt file and caffemodel file are all downloaded from your netdisk.

**Comment by alex-lysenko** [comment]
Try to use **yolov3_608_trt.prototxt** file instead **yolov3_608.prototxt**.

**Comment by bigyaofei** [comment]
I have tried yolov3_608_trt and yolov3_608 without upsample_param already, I find it is the concat layer that cause the problem.Like "layer80-route" , a concat layer with only one bottom, cause the segmentation fault error.  Do you know the reason?

**Comment by lewes6369** [comment]
Is it ok when you run with yolov3_608_trt.prototxt ？
Different with yolov3_608, the yolov3_608_trt proto commented the upsample_param and added the last yolo-det layer .

**Comment by scutzhe** [comment]
@alex-lysenko 
When using  **yolov3_608_trt.prototxt** file instead **yolov3_608.prototx**
It's success
