### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by sankim90** [lewes6369/TensorRT-Yolov3#21]
my env is 
ubuntu 16.04
opencv 3.4
cuda 9.2
nvidia drvier 384.130
TensorRT 5.0.2.6
cmake version 3.5.1
Make 4.1
Titan X pascal GPU

my cmake list is
sankim@sankim-desktop:~/TensorRT-Yolov3/build$ cmake ..
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.2 (found version "9.2") 
-- Found TensorRT headers at /usr/include/x86_64-linux-gnu
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so;/usr/lib/x86_64-linux-gnu/libnvparsers.so
-- Found TENSORRT: /usr/include/x86_64-linux-gnu  
-- Found CUDA: /usr/local/cuda-9.2 (found suitable exact version "9.2") 
-- Found OpenCV: /usr/local (found version "3.4.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sankim/TensorRT-Yolov3/build

and i run make

[10%] Building NVCC (Device) object tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o
-- Removing /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o
/usr/bin/cmake -E remove /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o
-- Generating dependency file: /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.NVCC-depend
/usr/local/cuda-9.2/bin/nvcc -M -D__CUDACC__ /home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/src/YoloLayer.cu -o /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.NVCC-depend -ccbin /usr/bin/c++ -m64 --std c++11 -Xcompiler ,\"-Wall\",\"-Ofast\",\"-Wfatal-errors\",\"-Wall\",\"-Ofast\",\"-Wfatal-errors\",\"-D_MWAITXINTRIN_H_INCLUDED\",\"-O3\",\"-DNDEBUG\" -D_FORCE_INLINES -Xcompiler -fPIC -DNVCC -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda-9.2/include -I/home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/include -I/usr/local/cuda-9.2/include
-- Generating temporary cmake readable file: /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.NVCC-depend -D output_file:FILEPATH=/home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp -P /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp to /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend
/usr/bin/cmake -E copy_if_different /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend
-- Removing /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp and /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.NVCC-depend
/usr/bin/cmake -E remove /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.depend.tmp /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o.NVCC-depend
-- Generating /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o
/usr/local/cuda-9.2/bin/nvcc /home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/src/YoloLayer.cu -c -o /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o -ccbin /usr/bin/c++ -m64 --std c++11 -Xcompiler ,\"-Wall\",\"-Ofast\",\"-Wfatal-errors\",\"-Wall\",\"-Ofast\",\"-Wfatal-errors\",\"-D_MWAITXINTRIN_H_INCLUDED\",\"-O3\",\"-DNDEBUG\" -D_FORCE_INLINES -Xcompiler -fPIC -DNVCC -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda-9.2/include -I/home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/include -I/usr/local/cuda-9.2/include
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9220): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9231): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9244): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9255): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9268): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9279): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9292): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9303): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9316): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9327): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9340): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9352): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9365): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9376): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9389): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9401): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9410): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9419): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9428): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9437): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9445): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9454): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9463): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9472): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9481): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9490): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9499): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9508): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9517): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9526): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9535): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9544): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(55): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(63): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(73): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(81): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(91): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(100): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(109): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(117): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(127): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(136): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(145): error: argument of type "void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(153): error: argument of type "void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10799): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10811): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10823): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10835): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10847): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10859): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10871): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10883): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10895): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10907): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10919): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10931): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10943): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10955): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10967): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10979): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(10989): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11000): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11009): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11020): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11029): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11040): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11049): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11060): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11069): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11080): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11089): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11100): error: argument of type "void *" is incompatible with parameter of type "float *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11109): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11120): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11129): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11140): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11149): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11160): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11169): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11180): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11189): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11200): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11209): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11220): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11229): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11240): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11249): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11260): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11269): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11280): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11289): error: argument of type "void *" is incompatible with parameter of type "long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11300): error: argument of type "void *" is incompatible with parameter of type "long long *"

/home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/src/YoloLayer.cu(32): warning: variable "a" was declared but never referenced

/home/sankim/TensorRT-Yolov3/tensorRTWrapper/code/src/YoloLayer.cu(47): warning: variable "a" was declared but never referenced

92 errors detected in the compilation of "/tmp/tmpxft_000010e0_00000000-6_YoloLayer.cpp1.ii".
-- Removing /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o
/usr/bin/cmake -E remove /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o
CMake Error at TrtNet_generated_YoloLayer.cu.o.cmake:266 (message):
  Error generating file
  /home/sankim/TensorRT-Yolov3/build/tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/./TrtNet_generated_YoloLayer.cu.o

tensorRTWrapper/code/CMakeFiles/TrtNet.dir/build.make:70: recipe for target 'tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o' failed
make[2]: *** [tensorRTWrapper/code/CMakeFiles/TrtNet.dir/src/TrtNet_generated_YoloLayer.cu.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'tensorRTWrapper/code/CMakeFiles/TrtNet.dir/all' failed
make[1]: *** [tensorRTWrapper/code/CMakeFiles/TrtNet.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

how can i run this?

**Comment by lewes6369** [comment]
Hi,@sankim90 ,I thought that it maybe a compiler error in the version. Your gcc version is not compatible with your TensorRT NVCC version. Try gcc 4.9/5.4 . If it doesn't work, just reinstall cuda and TensorRT.
