### ISSUE TITLE
CMake Error at CMakeLists.txt:17  

### ISSUE THREAD

**Issue by fengzifrank** [lewes6369/TensorRT-Yolov3#23]
-- Found TensorRT headers at /usr/include/x86_64-linux-gnu
-- Find TensorRT libs at /usr/lib/x86_64-linux-gnu/libnvinfer.so;/usr/lib/x86_64-linux-gnu/libnvinfer_plugin.so;/usr/lib/x86_64-linux-gnu/libnvparsers.so
CMake Error at CMakeLists.txt:17 (FIND_PACKAGE):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/opt/tensorrt/TensorRT-Yolov3/build/CMakeFiles/CMakeOutput.log".
See also "/opt/tensorrt/TensorRT-Yolov3/build/CMakeFiles/CMakeError.log".

 How to set Opencv variables？ Thank you

**Comment by fengzifrank** [comment]
Solved Just install opencv
https://blog.csdn.net/KYJL888/article/details/80799370

**Comment by lewes6369** [comment]
Thanks, you have already install the opencv by the instructions.So I could close the issue.
The Opencv, CUDNN and the TensorRT are all the 3rd libs, so you can install them by their official instructions and the libs can be found in the cmakeconfig.cmake using by the program.
