### ISSUE TITLE
ERROR: CaffeParser: ERROR: Attempting to access NULL weights ERROR: Parameter check failed at: ../builder/Network.cpp::addConvolution::66, condition: kernelWeights.values != nullptr

### ISSUE THREAD

**Issue by fengzifrank** [lewes6369/TensorRT-Yolov3#24]
####### input args#######
C=3;
H=608;
W=608;
caffemodel=./608/yolov3_608.caffemodel;
calib=;
class=80;
evallist=;
input=dog.jpg;
mode=fp32;
nms=0.450000;
outputs=yolo-det;
prototxt=./608/yolov3_608_trt.prototxt;
####### end args#######
init plugin proto: ./608/yolov3_608_trt.prototxt caffemodel: ./608/yolov3_608.caffemodel
Begin parsing model...
Weights for layer layer1-conv doesn't exist
ERROR: CaffeParser: ERROR: Attempting to access NULL weights
ERROR: Parameter check failed at: ../builder/Network.cpp::addConvolution::66, condition: kernelWeights.values != nullptr
error parsing layer type Convolution index 0
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)

How to deal with thank you

**Comment by lewes6369** [comment]
According to the console，“Weights for layer layer1-conv doesn't exist”， it seems that your caffemodel is not suitable for the prototxt. Do you download from the link or trained by yourself ? If Downloaded , try download one more time.
