### ISSUE TITLE
about calib_sample.txt

### ISSUE THREAD

**Issue by faedtodd** [lewes6369/TensorRT-Yolov3#28]
and what should i do with the error:
####### input args####### 
C=3;
H=608;
W=608;
caffemodel=./models/608/yolov3_608.caffemodel;
calib=./calib_sample.txt;
class=80;
evallist=;
input=./models/608/1.jpg;
mode=int8;
nms=0.450000;
outputs=yolo-det;
prototxt=./models/608/yolov3_608_trt.prototxt;
####### end args####### 
find calibration file,loading ...
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp, line 3648
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-ys8xiq/opencv-2.4.9.1+dfsg/modules/imgproc/src/color.cpp:3648: error: (-215) scn == 3 || scn == 4 in function cvtColor

Aborted (core dumped)

thanks a lot

**Comment by sukibean163** [comment]
calib_sample.txt:
/data/000001.jpg
/data/000002.jpg

but i dont know what's meaning...

**Comment by lewes6369** [comment]
Please add your calibration file paths in calib_sample.txt. It is used for the int8 calibration. More details check the official [link](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#optimizing_int8_c)

**Comment by faedtodd** [comment]
> Please add your calibration file paths in calib_sample.txt. It is used for the int8 calibration. For more details check the official [link](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#optimizing_int8_c)

thx, and what should i write into the calib_sample.txt, only photos or photos with label of each orther

**Comment by cong235** [comment]
> > Please add your calibration file paths in calib_sample.txt. It is used for the int8 calibration. For more details check the official [link](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#optimizing_int8_c)
> 
> thx, and what should i write into the calib_sample.txt, only photos or photos with label of each orther

As i know, it is just only photo, because it use for loading model with all layer.

**Comment by faedtodd** [comment]
> > > Please add your calibration file paths in calib_sample.txt. It is used for the int8 calibration. For more details check the official [link](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#optimizing_int8_c)
> > 
> > 
> > thx, and what should i write into the calib_sample.txt, only photos or photos with label of each orther
> 
> As i know, it is just only photo, because it use for loading model with all layer.

thx man
