### ISSUE TITLE
Eval Error

### ISSUE THREAD

**Issue by sankim90** [lewes6369/TensorRT-Yolov3#29]
My model's class num is 9
and Inference result is good

I want to eval my own model

I command next(LOAD_FROM_ENGINE): 
~/yolo_trt$ ./runYolov3  --W=608 --H=608 --class=9 --mode=fp16 --evallist=labels.txt

C=3;
H=608;
W=608;
caffemodel=yolov3.caffemodel;
calib=;
cam=off;
class=9;
evallist=labels.txt;
input=;
mode=fp16;
nms=0.450000;
outputs=yolo-det;
prototxt=yolov3_trt.prototxt;
####### end args####### 
Load model = yolov3_fp16.engine
*** deserializing
loading from eval list labels.txt
runYolov3: /home/keti-ev/yolo_trt/eval.cpp:67: float Tn::evalMAPResult(const std::__cxx11::list<std::vector<Tn::Bbox> >&, const std::__cxx11::list<std::vector<Tn::Bbox> >&, int, float): Assertion `bboxesList.size() == truthboxesList.size()' failed.
Aborted (core dumped)
---------------------------------------------------------------------------------------------------------------------------------
my labels.txt is
home/keti-ev/yolo_trt/scripts/minival2014/COCO_val2014_000000576031.jpg 1 [224.36, 78.74, 179.06, 390.47] 1 [265.79, 121.26, 30.08, 40.97] 1 [143.77, 112.02, 68.46, 113.47] 1 [141.9, 125.17, 31.24, 85.5]

/home/keti-ev/yolo_trt/scripts/minival2014/COCO_val2014_000000222458.jpg 1 [510.94, 206.13, 13.15, 27.51] 1 [534.23, 211.96, 7.58, 18.05] 1 [450.7, 196.12, 33.18, 87.33] 1 [600.46, 204.78, 14.82, 32.97] 1 [587.04, 205.55, 13.8, 33.02]

how can i evaluation that?

**Comment by lewes6369** [comment]
It looks like the label format error. It seems that you write the blank line in the two of the record and the first image path miss the head '/'. You can debug code or print the variable ("fileNames" and "groundTruth") for some information.
