### ISSUE TITLE
unable to create model with input size 416

### ISSUE THREAD

**Issue by MilkWithCoffee** [lewes6369/TensorRT-Yolov3#30]
Hi lewes,
thanks a lot for your work. I was able to successfully build yolov3 engines both with FP32 and int8 precision. With input size of 608.
Unfortunately, I fail with yolov3-416. What i did:

- download the 416 files from your googleDrive
- edit the parameters in /include/configs.h I assume you refer to this file in the Readme where it says "(need to modify include/YoloConfigs for YoloKernel)" ? 
- I tried playing around with NMS_THRESH, INPUT_WIDTH, and INPUT_HEIGHT variables in said file. I can see no difference in the output engine.

The engine runs fine, but produces a lot of random bounding boxes. Also the runtime of the 416 model is the same as for the 608 model, which seams strange.

Could you provide a more in detail explanation of how to create volov3-416 model please?
![result](https://user-images.githubusercontent.com/33390210/54559448-565a2a00-497d-11e9-84dd-b40190b71d22.jpg)

**Comment by cong235** [comment]
@MilkWithCoffee You should modify this file for 416: TensorRT-Yolov3/tensorRTWrapper/code/include/YoloConfigs.h

**Comment by lewes6369** [comment]
HI, @MilkWithCoffee 
As suggestion by @cong235 . The official model yolo 416 kernel is already written in the comments, just uncomment them. 
And make sure you do not load from the engine file ,because you changed the model.

**Comment by MilkWithCoffee** [comment]
Thank you very much. I had edited the wrong file.
Int8 model is running smoothly now.
