### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by Rahn80643** [lewes6369/TensorRT-Yolov3#31]
Has anyone tried batch inference, which means infer several images at the same time? 
I tried modify maxBatchSize inside TrtNet.cpp and execute doInference with multiple images, but I only get bounding boxes of the first image.

**Comment by lewes6369** [comment]
As talked [here](https://github.com/lewes6369/tensorRTWrapper/issues/5), I did not implement for more than one bs, so some work should have to be done before the batch infer.

**Comment by Rahn80643** [comment]
I've put the batch of images in an input array, and execute doInference with it. But I only get bounding boxes of the first image, the results of other images are zeros. 
According to the [post](https://github.com/lewes6369/tensorRTWrapper/issues/5), should I modify the setting inside plugin layers ?

**Comment by lewes6369** [comment]
Yes, you shoud implement enqueue funcs for batch version. If you need, I will add the batch infer next week.

**Comment by Rahn80643** [comment]
@lewes6369 
Thank you for your reply, and thank you for your update for batch inference.
I'm trying to implement the code in YoloLayer.cu, but I still cannot get the results of the 2nd image.

**Comment by lewes6369** [comment]
Hi @Rahn80643 , I'm sorry to add the batch infer so late because of being stuck in other things.Now I have already add the batch inference. Please try it again,thanks.

**Comment by Rahn80643** [comment]
@lewes6369 
Thank you for your update, it really helps.

**Comment by ttdd11** [comment]
@Rahn80643 Did you end up getting the batch working?
