### ISSUE TITLE
Link for caffe models

### ISSUE THREAD

**Issue by HilmiK** [lewes6369/TensorRT-Yolov3#4]
Hello,

Could you give a link to download sample caffemodels ? And give a clue for training custom models if it is possible using caffe? Or just conversion from darknet ?

**Comment by lewes6369** [comment]
Hi, Hilmik. You can check the link https://pan.baidu.com/s/1exXKXw7eFIpfBlO3q9VBTQ password: es12 It depends on the official 608-yolov3-cfg. 

->And give a clue for training custom models if it is possible using caffe? Or just conversion from darknet ?
Of course,  you can train the model in caffe, but you should add the preprocess and postprocess as the sample, use the caffe commit https://github.com/BVLC/caffe/pull/6384/commits/4d2400e7ae692b25f034f02ff8e8cd3621725f5c.  And also you can train and conversion from darknet.

**Comment by HilmiK** [comment]
Thanks for reply.
