### ISSUE TITLE
how to build so file 

### ISSUE THREAD

**Issue by scutzhe** [lewes6369/TensorRT-Yolov3#41]
#build so_file
set(SRC main.cpp eval.cpp dataReader.cpp)
add_library(yolov3 SHARED ${SRC})
target_link_libraries(yolov3 TrtNet ${OpenCV_LIBS})

#generate so_file
install(TARGETS yolov3 DESTINATION ${CMAKE_CURRENT_SOURCE_DIR}/install/)

CMakeList.txt add these lines  but failed

**Comment by VeryVery** [comment]
can u show more error detail?

**Comment by scutzhe** [comment]
> can u show more error detail?
