### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by adhirmndl** [lewes6369/TensorRT-Yolov3#42]
~/TensorRT-Yolov3$ cd build && cmake .. && make && make install
-- Found TensorRT headers at /home/ivis/TensorRT-5.0.2.6/include
-- Find TensorRT libs at /home/ivis/TensorRT-5.0.2.6/lib/libnvinfer.so;/home/ivis/TensorRT-5.0.2.6/lib/libnvinfer_plugin.so;/home/ivis/TensorRT-5.0.2.6/lib/libnvparsers.so
-- Configuring done
WARNING: Target "runYolov3" requests linking to directory "/home/ivis/TensorRT-5.0.2.6/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TrtNet" requests linking to directory "/home/ivis/TensorRT-5.0.2.6/lib/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/ivis/TensorRT-Yolov3/build
[ 60%] Built target TrtNet
[ 70%] Linking CXX executable runYolov3
CMakeFiles/runYolov3.dir/main.cpp.o: In function `Tn::PluginFactory::createPlugin(char const*, void const*, unsigned long)':
main.cpp:(.text._ZN2Tn13PluginFactory12createPluginEPKcPKvm[_ZN2Tn13PluginFactory12createPluginEPKcPKvm]+0xfe): undefined reference to `nvinfer1::plugin::createPReLUPlugin(void const*, unsigned long)'
CMakeFiles/runYolov3.dir/main.cpp.o: In function `Tn::PluginFactory::createPlugin(char const*, nvinfer1::Weights const*, int)':
main.cpp:(.text._ZN2Tn13PluginFactory12createPluginEPKcPKN8nvinfer17WeightsEi[_ZN2Tn13PluginFactory12createPluginEPKcPKN8nvinfer17WeightsEi]+0xf6): undefined reference to `nvinfer1::plugin::createPReLUPlugin(float)'
tensorRTWrapper/code/libTrtNet.a(TrtNet.cpp.o): In function `Tn::trtNet::loadModelAndCreateEngine(char const*, char const*, int, nvcaffeparser1::ICaffeParser*, nvcaffeparser1::IPluginFactory*, nvinfer1::IInt8Calibrator*, nvinfer1::IHostMemory*&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
TrtNet.cpp:(.text+0x135): undefined reference to `createInferBuilder_INTERNAL'
TrtNet.cpp:(.text+0x2b2): undefined reference to `nvcaffeparser1::shutdownProtobufLibrary()'
tensorRTWrapper/code/libTrtNet.a(TrtNet.cpp.o): In function `Tn::trtNet::trtNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::vector<float, std::allocator<float> >, std::allocator<std::vector<float, std::allocator<float> > > > const&, Tn::RUN_MODE, int)':
TrtNet.cpp:(.text+0xe01): undefined reference to `nvcaffeparser1::createCaffeParser()'
TrtNet.cpp:(.text+0x1076): undefined reference to `createInferRuntime_INTERNAL'
tensorRTWrapper/code/libTrtNet.a(TrtNet.cpp.o): In function `Tn::trtNet::trtNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
TrtNet.cpp:(.text+0x1576): undefined reference to `createInferRuntime_INTERNAL'
collect2: error: ld returned 1 exit status
CMakeFiles/runYolov3.dir/build.make:167: recipe for target 'runYolov3' failed
make[2]: *** [runYolov3] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/runYolov3.dir/all' failed
make[1]: *** [CMakeFiles/runYolov3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
ivis@sbi-analytic2:~/TensorRT-Yolov3/build$

**Comment by lewes6369** [comment]
It seems the version is not supported. Please try to run in TensorRT version 4.0.1.6 or above
