### ISSUE TITLE
Detected object in TensorRT VS Darknet model

### ISSUE THREAD

**Issue by Rahn80643** [lewes6369/TensorRT-Yolov3#44]
Hi, when I convert my YOLOv3 model to tensorRT, some objects that can be detected in YOLOv3 are not detected in TensorRT with FP32 mode.

Objects detected in Darknet YOLOv3
![image](https://user-images.githubusercontent.com/8951991/58065654-06842300-7bb9-11e9-8ec0-229f17065b54.png)

Objects detected in TensorRT YOLOv3
![image](https://user-images.githubusercontent.com/8951991/58065746-4b0fbe80-7bb9-11e9-9214-95c45bf4f62a.png)

Should I modify the training data or modify some settings in TensorRT ?

**Comment by lewes6369** [comment]
Is this your own model? please try to check the yolo config  in "tensorRTWrapper/code/include/YoloConfigs.h" and the nms threshold.

**Comment by Rahn80643** [comment]
I solved this by modifying the training data, and retrain the model.
Thank you.
