### ISSUE TITLE
How to run TensorRT-Yolov3 on the second graphics cards？

### ISSUE THREAD

**Issue by neuwyq** [lewes6369/TensorRT-Yolov3#47]
How can I run the program on the second graphics card? I tried to modify cudaStream_t but it didn't work.
Thank you in advance!

**Comment by lewes6369** [comment]
If you just want run program in a second graphic card,you can just use the CUDA_VISIBLE_DEVICES to set current graphic card in runing. If you want to run a single program with different model runing in different graphics ,maybe you should check the tensorRT docs to find some tips.I did not focus on yet.

**Comment by neuwyq** [comment]
> 
> 
> If you just want run program in a second graphic card,you can just use the CUDA_VISIBLE_DEVICES to set current graphic card in runing. If you want to run a single program with different model runing in different graphics ,maybe you should check the tensorRT docs to find some tips.I did not focus on yet.

I'm sorry to reply to you so late. I've made it by using CUDA_VISIBLE_DEVICES. Thank you again for your reply!
