### ISSUE TITLE
caffe model

### ISSUE THREAD

**Issue by Riwaly** [lewes6369/TensorRT-Yolov3#6]
Hi, I can't use my yolov3-caffe model to get right result, could you please give a link to share your your caffemodel and proto.txt files, thanks!

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
hi @Riwaly 
I can't get the right result too, the author's caffemodel is here:[](https://github.com/lewes6369/tensorRTWrapper/issues/1)  
can you share your result with me?  I test the fp32 and fp16 , it takes a long time with poor precision  I dont know the reason.

I use jetson xavier.

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
hi @Riwaly
I can't get the right result too, the author's caffemodel is [here:](https://github.com/lewes6369/tensorRTWrapper/issues/1)
can you share your result with me? I test the fp32 and fp16 , it takes a long time with poor precision I dont know the reason.

I use jetson xavier.

**Comment by Riwaly** [comment]
Hi @Yuuuuuuuuuuuuuuuuuummy 
Thanks for your link, but the download link is missing, could you give me a new link for the caffemodel and proto.txt files!
When I parsing my yolov3 caffemodel on TX2, the result like this:
init plugin proto: data/yolov3.prototxt caffemodel: data/yolov3.caffemodel
Begin parsing model...
Caffe Parser: ReLU negative slope is not supported
error parsing layer type ReLU index 3
ERROR: ssd_error_log: Fail to parse

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
oh sorry.. yesterday I click the link is ok,  i upload the model in this [link](https://pan.baidu.com/s/1jBL3KER22dE2R_F7N51u4g)
Your error can be fixed by the issue in the previous link i commented
would you plz tell me your result finally?  many thanks!!!!

**Comment by lewes6369** [comment]
Hi，@Riwaly ，maybe your LeakyRelu layers are not named as layer3-act,layer4-act,layer6-act ...  
see this link https://github.com/lewes6369/tensorRTWrapper/issues/1

You can modify the 'isLeakyRelu' function in "PluginFactory.h" to your leaky ReLU name which written in your yolov3 prototxt.

Thanks.

**Comment by Riwaly** [comment]
hi @Yuuuuuuuuuuuuuuuuuummy 
Thanks for your reply, My error was caused by the version of TensorRT, I can get the right result now.
