### ISSUE TITLE
ERROR: Cuda initialization failure with error 35. Please check cuda installation

### ISSUE THREAD

**Issue by ZhangYouYu-09** [lewes6369/TensorRT-Yolov3#61]
Hello @lewes6369 . 

cuda9.2, NVIDIA-SMI 384.130,  
i run the Yolov3 and some issue occured

user@user-S2600WT2R:~/youyu/TensorRT-Yolov3-Github$ ./install/runYolov3 --caffemodel=v3face/yolov3-widerface_final.caffemodel --prototxt=v3face/yolov3_608_trt.prototxt --input=test.jpg --W=608 --H=608 --class=1
####### input args####### 
C=3;
H=608;
W=608;
caffemodel=v3face/yolov3-widerface_final.caffemodel;
calib=;
class=1;
evallist=;
input=test.jpg;
mode=fp32;
nms=0.450000;
outputs=yolo-det;
prototxt=v3face/yolov3_608_trt.prototxt;
####### end args####### 
init plugin proto: v3face/yolov3_608_trt.prototxt caffemodel: v3face/yolov3-widerface_final.caffemodel
ERROR: Cuda initialization failure with error 35. Please check cuda installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html.
Segmentation fault (core dumped)

**Comment by lewes6369** [comment]
as the info shows, "Cuda initialization failure with error 35. Please check cuda installation".And can you run other the official tensorRT samples? It should be failed, too".

**Comment by ZhangYouYu-09** [comment]
thanks

Best Regard
――――――――
张友玉
Tel:15775977398

________________________________

**Comment by 1LOVESJohnny** [comment]
I met the same problem. In my case, it's caused by mismatched CUDA versions between my local environment CUDA 10.1 and within a specific docker CUDA 10.2. I updated my local environment to CUDA 10.2 and then the problem is gone.

**Comment by tangsipeng** [comment]
update driver of CUDA 10.2 then done

**Comment by zhangxiaoya** [comment]
may be your Nvidia Driver failed, try run `nvidia-smi`, if get error message, re-install nvidia driver can fix it.
