### ISSUE TITLE
Is the data type of the yolo3 model under the darknet or caffe framework is double precision?

### ISSUE THREAD

**Issue by jianwu585218** [lewes6369/TensorRT-Yolov3#65]
Thanks for your work~
I have a question，that is :  
Is the data type of the yolo3 model under the darknet or caffe framework is double precision（FP64）?
![image](https://user-images.githubusercontent.com/34296200/64112416-eb30d280-cdb9-11e9-97c5-edcfca501cf1.png)

**Comment by lewes6369** [comment]
It is also float32 in caffe.

**Comment by jianwu585218** [comment]
Thanks 
Why the second line improved a lot, it is also float32 which as same as caffe? Due to the framework ，or other way(such as Layer & Tensor Fusion)?

**Comment by lewes6369** [comment]
It benefits to TensorRT. See here https://developer.nvidia.com/tensorrt

**Comment by jianwu585218** [comment]
Thanks for your repley~
Have you test the  yolo3-416 's  inference time under float16（by TensorRT）？

**Comment by lewes6369** [comment]
My graphics cards did not support fast fp16, just take a try on your card.
