### ISSUE TITLE
can not find output named yolo-det

### ISSUE THREAD

**Issue by jgqandsh** [lewes6369/TensorRT-Yolov3#72]
my develop environmnet is ubuntu18.04, cuda10.0, cudnn 7.6 , tensorrt 6.0.1.5
when i run `./install/runYolov3 --caffemodel=./yolov3_608.caffemodel --prototxt=./yolov3_608.prototxt --input=./test.jpg --W=608 --H=608 --class=80
`
i get the info: 
> ####### input args####### 
C=3;
H=608;
W=608;
batchsize=1;
caffemodel=./yolov3_608.caffemodel;
calib=;
class=80;
enginefile=;
evallist=;
input=./test.jpg;
mode=fp32;
nms=0.450000;
outputs=yolo-det;
prototxt=./yolov3_608.prototxt;
####### end args#######
init plugin proto: ./yolov3_608.prototxt caffemodel: ./yolov3_608.caffemodel
Begin parsing model...
End parsing model...
can not find output named yolo-det
Segmentation fault (core dumped)

Can you help me? Thank you

**Comment by mbahaa** [comment]
You need to load the tensorrt-compatible prototxt file `yolov3_608_trt.prototxt` not `yolov3_608.prototxt`

**Comment by jgqandsh** [comment]
@mbahaa 
> You need to load the tensorrt-compatible prototxt file `yolov3_608_trt.prototxt` not `yolov3_608.prototxt`

I changed the yolov3_608.prototxt to yolov3_608_trt.prototxt. It works well. Thank you very much!. I will close the issue. thank you again.

**Comment by jgqandsh** [comment]
@mbahaa  told me to change the yolov3_608.prototx to yolov3_608_trt.prototxt, it runned well, i get a output. Thanks his answer.
