### ISSUE TITLE
Read Engine from Python

### ISSUE THREAD

**Issue by jefflgaol** [lewes6369/TensorRT-Yolov3#74]
I tried to use the engine produced by your C++ code and called it via Python.

Below is the code that I used:
```
engine_file_path = '/home/cwlab/ALPR/TensorRT-Yolov3-master/yolov3_int8.engine'
TRT_LOGGER = trt.Logger()
def get_engine(path):
	with open(path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
		return runtime.deserialize_cuda_engine(serialized_engine=f.read())

def main():
	print("Reading engine from file {}".format(engine_file_path))
	engine = get_engine(engine_file_path)

if __name__ == '__main__':
	main()
```

But, I get this following error:
[TensorRT] ERROR: Serialized engine contains plugin, but no plugin factory was provided. To deserialize an engine without a factory, please use IPluginV2 instead.

Do you mind sharing what should I do? Or I simply can't import the engine without the shared library, because I can't find one. Thank you.

**Comment by lewes6369** [comment]
The repo was built based on TensorRT v4.0.1.6 at first which may not suitable for the newer python version .Maybe you need to migrate the code to the TensorRT v5 or later to meet the IPluginV2.

**Comment by faedtodd** [comment]
> I tried to use the engine produced by your C++ code and called it via Python.
> 
> Below is the code that I used:
> 
> ```
> engine_file_path = '/home/cwlab/ALPR/TensorRT-Yolov3-master/yolov3_int8.engine'
> TRT_LOGGER = trt.Logger()
> def get_engine(path):
> 	with open(path, "rb") as f, trt.Runtime(TRT_LOGGER) as runtime:
> 		return runtime.deserialize_cuda_engine(serialized_engine=f.read())
> 
> def main():
> 	print("Reading engine from file {}".format(engine_file_path))
> 	engine = get_engine(engine_file_path)
> 
> if __name__ == '__main__':
> 	main()
> ```
> 
> But, I get this following error:
> [TensorRT] ERROR: Serialized engine contains plugin, but no plugin factory was provided. To deserialize an engine without a factory, please use IPluginV2 instead.
> 
> Do you mind sharing what should I do? Or I simply can't import the engine without the shared library, because I can't find one. Thank you.

hello, have u solve the problem

**Comment by sondv2** [comment]
Hi @jefflgaol 
Have U solve the problem ?
We are facing with it.

**Comment by jefflgaol** [comment]
I haven't solved it yet. So, I trained my own model using Darknet and create my own engine. The tutorial was provided very clear in NVIDIA Documentation.

**Comment by bobbilichandu** [comment]
@jefflgaol  Have you solved this?
Can you share the link to tutorial please. Thanks!
