### ISSUE TITLE
Can you explain what does the code mean for ?

### ISSUE THREAD

**Issue by Stephenfang51** [lewes6369/TensorRT-Yolov3#85]
As the following 
`list(APPEND CUDA_NVCC_FLAGS "-D_FORCE_INLINES -Xcompiler -fPIC")`

I don't understand "-D_FORCE_INLINES -Xcompiler -fPIC"

**Comment by lewes6369** [comment]
`"-D_FORCE_INLINES "` - ask compiler for forcing inline funcs;
`"-Xcompiler"` - is just to tell nvcc the non-nvcc option behind it, in the cmd is `"-fPIC"`;
`"-fPIC"` - loading shared library with Position-Independent Code;

**Comment by Stephenfang51** [comment]
@lewes6369  Thanks so much
