### ISSUE TITLE
Inference Time Issue

### ISSUE THREAD

**Issue by VigorPoppy** [lewes6369/TensorRT-Yolov3#9]
Hi, when I was trying to generate .engine the error occured below:
init plugin proto: ./yolov3_lite_mod.prototxt caffemodel: ./yolov3_lite_mod.caffemodel

Begin parsing model...
could not parse layer type Upsample
ERROR: ssd_error_log: Fail to parse
Segmentation fault (core dumped)

I have checked the layer Upsample and the example you provided in the readme work fine. So could you please check the problem? Thanks!!

**Comment by lewes6369** [comment]
Hi,@VigorPoppy ,make sure your prototxt is the same name written in PluginFactory.h , name as  "layer86-upsample ,layer98-upsample"

**Comment by VigorPoppy** [comment]
Thanks for your reply! I have checked it and renamed the layers. It seems work well.  There is another problem. When I use net->forward in caffe. The inference time of my own caffemodel is about 40-50ms. In your code with the same caffemodel, the inference time is about 60ms. Speed under FP16 mode(70ms) -- even slower than FP32. And the precision is also decrease a lot both in FP32 and FP16.

**Comment by lewes6369** [comment]
Hi @VigorPoppy do you test in the same structure? Maybe you should check whether the yolo config is the same. The running will output the time cost , can you put the output log here ? And shall you share your gpu device type? In testing, the precision is the same in fp32 as caffe.

**Comment by lewes6369** [comment]
And could you give the the prototxt and YoloConfigs info here?

**Comment by VigorPoppy** [comment]
Thanks for your reply! The input resolution and all the other config info are the same.  The code I used in caffe is:
`clock_t time;
time = clock();
net_->Forward();
printf("Predicted in %f seconds.\n",  sec(clock() - time));`

the result is:
`Predicted in 0.058343 seconds.
_003240 1 0.999893 759 618 859 801
_003240 1 0.999175 666 587 785 806
_003240 1 0.999078 868 469 1168 1101
_003240 1 0.994044 507 597 607 779
_003240 1 0.866441 1032 491 1335 1129
_003240 1 0.825324 631 631 670 705
Predicted in 0.047801 seconds.
_003241 1 0.99984 766 615 870 805
_003241 1 0.999573 668 588 790 807
_003241 1 0.999024 515 600 613 782
_003241 1 0.998149 882 476 1171 1101
_003241 1 0.93445 1040 499 1343 1117
_003241 1 0.267726 634 632 673 706
Predicted in 0.051120 seconds.
_003242 1 0.99997 514 594 619 791
_003242 1 0.999829 771 614 871 805
_003242 1 0.999571 665 569 799 825
_003242 1 0.998126 892 474 1193 1097
_003242 1 0.980864 1032 496 1352 1118
_003242 1 0.517655 639 632 677 704
Predicted in 0.055676 seconds.
_003243 1 0.999964 773 614 875 806
_003243 1 0.999836 516 593 618 792
_003243 1 0.998531 665 568 801 820
_003243 1 0.997485 894 483 1224 1080
_003243 1 0.993176 1077 518 1388 1092
_003243 1 0.988622 852 627 952 821
_003243 1 0.624096 640 632 678 702
Predicted in 0.055876 seconds.
_003244 1 0.999974 785 619 881 812
_003244 1 0.999909 520 591 624 789
_003244 1 0.999094 860 629 957 824
_003244 1 0.998772 667 573 804 817
_003244 1 0.997068 914 474 1236 1102
_003244 1 0.961674 1086 507 1393 1103
_003244 1 0.50607 648 634 687 703
Predicted in 0.055807 seconds.
_003245 1 0.99998 784 620 888 814
_003245 1 0.99992 523 590 628 789
_003245 1 0.999756 866 632 966 827
_003245 1 0.998979 673 570 809 820
_003245 1 0.996583 925 474 1236 1111
_003245 1 0.855668 1110 524 1413 1083
_003245 1 0.579327 654 633 693 707
Predicted in 0.051894 seconds.
_003246 1 0.999946 784 621 890 819
_003246 1 0.999903 530 589 640 796
_003246 1 0.99956 876 633 975 840
_003246 1 0.998763 936 462 1238 1124
_003246 1 0.998218 675 576 812 817
_003246 1 0.92333 1138 506 1429 1105
_003246 1 0.397051 659 634 698 705`

The log in your old version code is:
`Time taken for inference is 72.3779 ms.
conv0 + conv0/relu                       0.573ms
conv1 + conv1/relu                       3.041ms
conv2 + conv2/relu                       3.843ms
conv3 + conv3/relu input reformatter 0   0.579ms
conv3 + conv3/relu                       2.607ms
conv4 + conv4/relu                       1.840ms
conv5 + conv5/relu                       2.981ms
conv6 + conv6/relu                       1.981ms
conv7 + conv7/relu                       4.091ms
conv8 + conv8/relu                       4.027ms
conv9 + conv9/relu                       4.036ms
conv10 + conv10/relu                     4.190ms
conv11 + conv11/relu                     3.789ms
conv12 + conv12/relu                     2.699ms
conv13 + conv13/relu                     5.152ms
conv15 + conv15/relu                     5.047ms
upsample_1 input reformatter 0           0.068ms
upsample_1                               0.835ms
upsample_1 output reformatter 0          0.368ms
conv15_e + conv15_e/relu                 0.590ms
conv17 + conv17/relu                     3.504ms
conv17 + conv17/relu output reformatter  0.137ms
conv18 + conv18/relu                     6.454ms
conv18 + conv18/relu output reformatter  0.176ms
upsample_2                               1.372ms
conv18_e + conv18_e/relu                 0.782ms
conv18_e + conv18_e/relu output reformat 0.134ms
conv21 + conv21/relu                     3.268ms
conv20 + conv20/relu                     3.077ms
conv19 + conv19/relu                     3.892ms
conv22_1cls                              0.088ms
conv22_1cls output reformatter 0         0.005ms
conv23_1cls                              0.126ms
conv24_1cls input reformatter 0          0.234ms
conv24_1cls                              0.193ms
Time over all layers: 75.782`

**Comment by lewes6369** [comment]
The proto layer names seem different from mine, will the leaky relu layers also meeting names in PluginFactory?  Did you convert your darknet by the repo https://github.com/ChenYingpeng/caffe-yolov3 ? Does your device support faster fp16?

**Comment by lewes6369** [comment]
here is my test result in GTX 1060.  No layer will more than 2ms.

layer1-conv                              0.484ms
layer1-act                               0.600ms
layer2-conv                              0.908ms
layer2-act                               0.620ms
layer3-conv                              0.260ms
layer3-act                               0.152ms
layer4-conv                              0.656ms
layer4-act                               0.300ms
layer5-shortcut                          0.452ms
layer6-conv                              1.172ms
layer6-act                               0.152ms
layer7-conv                              0.154ms
layer7-act                               0.077ms
layer8-conv                              0.563ms
layer8-act                               0.152ms
layer9-shortcut                          0.227ms
layer10-conv                             0.146ms
layer10-act                              0.078ms
layer11-conv                             0.553ms
layer11-act                              0.154ms
layer12-shortcut                         0.230ms
layer13-conv                             0.872ms
layer13-act                              0.078ms
layer14-conv                             0.123ms
layer14-act                              0.040ms
layer15-conv                             0.567ms
layer15-act                              0.075ms
layer16-shortcut                         0.116ms
layer17-conv                             0.120ms
layer17-act                              0.039ms
layer18-conv                             0.555ms
layer18-act                              0.076ms
layer19-shortcut                         0.117ms
layer20-conv                             0.125ms
layer20-act                              0.039ms
layer21-conv                             0.553ms
layer21-act                              0.076ms
layer22-shortcut                         0.116ms
layer23-conv                             0.127ms
layer23-act                              0.040ms
layer24-conv                             0.554ms
layer24-act                              0.076ms
layer25-shortcut                         0.116ms
layer26-conv                             0.126ms
layer26-act                              0.040ms
layer27-conv                             0.561ms
layer27-act                              0.075ms
layer28-shortcut                         0.117ms
layer29-conv                             0.140ms
layer29-act                              0.039ms
layer30-conv                             0.550ms
layer30-act                              0.075ms
layer31-shortcut                         0.117ms
layer32-conv                             0.121ms
layer32-act                              0.039ms
layer33-conv                             0.554ms
layer33-act                              0.075ms
layer34-shortcut                         0.115ms
layer35-conv                             0.135ms
layer35-act                              0.039ms
layer36-conv                             0.549ms
layer36-act                              0.076ms
layer37-shortcut                         0.120ms
layer38-conv                             1.033ms
layer38-act                              0.038ms
layer39-conv                             0.139ms
layer39-act                              0.019ms
layer40-conv                             1.484ms
layer40-act                              0.038ms
layer41-shortcut                         0.060ms
layer42-conv                             0.133ms
layer42-act                              0.019ms
layer43-conv                             0.771ms
layer43-act                              0.038ms
layer44-shortcut                         0.059ms
layer45-conv                             0.127ms
layer45-act                              0.018ms
layer46-conv                             1.085ms
layer46-act                              0.038ms
layer47-shortcut                         0.060ms
layer48-conv                             0.139ms
layer48-act                              0.019ms
layer49-conv                             0.774ms
layer49-act                              0.037ms
layer50-shortcut                         0.059ms
layer51-conv                             0.129ms
layer51-act                              0.019ms
layer52-conv                             0.774ms
layer52-act                              0.038ms
layer53-shortcut                         0.061ms
layer54-conv                             0.127ms
layer54-act                              0.018ms
layer55-conv                             0.778ms
layer55-act                              0.038ms
layer56-shortcut                         0.060ms
layer57-conv                             0.129ms
layer57-act                              0.020ms
layer58-conv                             0.785ms
layer58-act                              0.038ms
layer59-shortcut                         0.060ms
layer60-conv                             0.126ms
layer60-act                              0.019ms
layer61-conv                             0.777ms
layer61-act                              0.038ms
layer62-shortcut                         0.062ms
layer63-conv                             1.126ms
layer63-act                              0.019ms
layer64-conv                             0.132ms
layer64-act                              0.008ms
layer65-conv                             1.166ms
layer65-act                              0.019ms
layer66-shortcut                         0.032ms
layer67-conv                             0.134ms
layer67-act                              0.008ms
layer68-conv                             1.133ms
layer68-act                              0.019ms
layer69-shortcut                         0.032ms
layer70-conv                             0.130ms
layer70-act                              0.009ms
layer71-conv                             1.114ms
layer71-act                              0.019ms
layer72-shortcut                         0.033ms
layer73-conv                             0.129ms
layer73-act                              0.008ms
layer74-conv                             1.170ms
layer74-act                              0.019ms
layer75-shortcut                         0.033ms
layer76-conv                             0.133ms
layer76-act                              0.008ms
layer77-conv                             1.806ms
layer77-act                              0.019ms
layer78-conv                             0.135ms
layer78-act                              0.008ms
layer79-conv                             1.116ms
layer79-act                              0.019ms
layer80-conv                             0.128ms
layer80-act                              0.009ms
layer81-conv                             1.552ms
layer81-act                              0.019ms
layer82-conv                             0.093ms
layer80-conv copy                        0.010ms
layer85-conv                             0.048ms
layer85-act                              0.005ms
layer86-upsample                         0.036ms
layer86-upsample copy                    0.023ms
layer88-conv                             0.243ms
layer88-act                              0.020ms
layer89-conv                             0.801ms
layer89-act                              0.038ms
layer90-conv                             0.130ms
layer90-act                              0.020ms
layer91-conv                             0.779ms
layer91-act                              0.038ms
layer92-conv                             0.127ms
layer92-act                              0.019ms
layer93-conv                             0.780ms
layer93-act                              0.039ms
layer94-conv                             0.134ms
layer92-conv copy                        0.019ms
layer97-conv                             0.039ms
layer97-act                              0.008ms
layer98-upsample                         0.067ms
layer98-upsample copy                    0.042ms
layer100-conv                            0.174ms
layer100-act                             0.038ms
layer101-conv                            0.560ms
layer101-act                             0.075ms
layer102-conv                            0.127ms
layer102-act                             0.039ms
layer103-conv                            0.550ms
layer103-act                             0.076ms
layer104-conv                            0.138ms
layer104-act                             0.040ms
layer105-conv                            0.553ms
layer105-act                             0.075ms
layer106-conv                            0.222ms
yolo-det                                 0.205ms

**Comment by VigorPoppy** [comment]
I test my model on TX2( which support fp16). The model was design and modified from yolov3-lite(detection for one class). I only use relu instead of L-relu. So I thought the L-relu would not be used in PluginFactory.h.

**Comment by lewes6369** [comment]
@VigorPoppy I test the 416 model in GTX 1060. No layer will more than 1ms. Do you modify your yolo model ? in the official the conv layer are 76. But the caffemodel you used seems only 24.  Can you share some details ?

**Comment by lewes6369** [comment]
OK. I will take the git a try.

**Comment by VigorPoppy** [comment]
This is the [prototxt](https://drive.google.com/open?id=186jMhdfqSY8_OHsYHFdAyUfr7hOQoyob) and [caffemodel](https://drive.google.com/open?id=1BD0uFJvz6JG4xyQ4p5tteb8bXvwiMB2I) I used on TX2.

**Comment by lewes6369** [comment]
I tried the prototxt. It is the 320 size not the 416. And in my code the "DepthwiseConvolution" did not implement by the plugin yet, how you processed the model?

**Comment by VigorPoppy** [comment]
You could tried the model I upload:
https://drive.google.com/file/d/1BD0uFJvz6JG4xyQ4p5tteb8bXvwiMB2I/view
https://drive.google.com/file/d/186jMhdfqSY8_OHsYHFdAyUfr7hOQoyob/view

**Comment by lewes6369** [comment]
The prototxt seems the training prototxt. The engine is related to gpu. So I can't run it directly. 

I test the the model on gpu GTX 1060 .
In tensorRT , fp32 costs 10.069ms ,  int8 costs 8.936ms. 
In caffe, it costs 49.968ms.
Caffe is much slower than tensorRT. 

Please check the time cost in TX2.

**Comment by lewes6369** [comment]
Make sure that no other thing effects running inference.

**Comment by VigorPoppy** [comment]
Thanks for your acvice. The result of TX2 is still strange and I will test my model on the desktop GPU first and then report you the log.

**Comment by VigorPoppy** [comment]
Hi, the problem of time inference is reasonable now. There is  another question that the accuracy of my model in FP32 and in FP16 mode is much worse than that in caffe. I don't think the accuracy of FP32 should be reduced so much. What do you think is the cause? Thanks!

**Comment by eric612** [comment]
@VigorPoppy 
Or you can try non-merge batchnorm model first ?

**Comment by VigorPoppy** [comment]
@eric612 Thanks for your advice! I will have a try and report you the result. The merged model test on caffe  works fine and the performance decrease dramatically in TRT(FP32 and 16). I hope the non-merged model could show a good result.

**Comment by lewes6369** [comment]
@VigorPoppy Hi,So what is the reason of the time problem. I tested some different TR models, and the fp32 is the same within caffe . Did you do yolo layer by caffe ? or only run the yolo and detectionOut in customer cpu layer?

Can you share me the trt used prototxt and the caffe used prototxt? Also with the "YoloConfigs.h" and repo commit id. I will have a check in the repo. 
Thanks.

**Comment by VigorPoppy** [comment]
@lewes6369 Hi, the problem caused by upsample layer. I used the deconvolution layer as upsample and it cost a lot of time and the depthwise convolution layer get a bad performance in TensorRT4 and it has been fixed in TensorRT5.
For the second question. I used the yolo layer by add a caffe layer( done by @eric612  https://github.com/eric612/MobileNet-YOLO.git).
This is the [trt prototxt](https://drive.google.com/open?id=1Ua-l1ABtPrD0AYrORJxMtKUoIhR0XsrI) and  [caffe prototxt](https://drive.google.com/open?id=1j07A0EFyt35pI8f77UDkiVfPrqHCVcjJ), [YoloConfig.h](https://drive.google.com/open?id=115Dz_1RUekhkhAZreHm6RqYhM4TnMTKO). Sorry, I don't quite understand what you said “repo commit id. I will have a check in the repo.” Thanks!!

**Comment by eric612** [comment]
@VigorPoppy 
Can I ask a question about the fps on tx2 by using the model , I'm very interesting it.

**Comment by VigorPoppy** [comment]
@eric612 The 3scle model based on your lite model(scale) could run about 20FPS on the webcam with input size 416*416. The inference time is about  36ms. FPSI mentioned above computed include the time of prepocess(image resize) and postprocess(nms). I replace the upsample layer type "Deconvolution" with the type "Upsample" because it is time consuming. And so I remove the maxpooling layer and replace elementwise layer with concat layer bacause the channel is mismatch. I think there's still a lot of metods for improvement in speed, but I may not have found the right way yet.

**Comment by eric612** [comment]
@VigorPoppy 
Thanks for your reply , compare with ssd on tx2 , like below
https://github.com/chenzhi1992/TensorRT-SSD
https://github.com/Robert-JunWang/Pelee/issues/43

* The pelee+ssd can run 70 fps + on tx2 , it's very cool . 
* So currently , I try to find the time consuming component, and thanks your reply again

**Comment by VigorPoppy** [comment]
@eric612 Hi, I have tested the MobileNet-SSD on TX2, too. With input 300*300. It could run about 30 FPS on webcam.  I talked to another code author who calculated FPS in the following way: 1/(inference time). It seems higher. A lot of time cost by image transmitting and processing. Nvidia has propose the deepstream for video accelerating. I think this is very helpful for real-time detection.

**Comment by VigorPoppy** [comment]
@eric612 I test the no-merge model but the performance seems still to be poor. I thought it may caused by difference of the implement of  yolo layer？

**Comment by eric612** [comment]
@VigorPoppy 
I see this project was used "letterbox resize" , did your model training parm with "FIT_LARGE_SIZE_AND_PAD" or "WARP" ?

**Comment by VigorPoppy** [comment]
@eric612 I used the "FIT_LARGE_SIZE_AND_PAD" mode in training.

**Comment by eric612** [comment]
I search this resize code in main.cpp in project. I guess it use warp resize , can you write down the image , and check the image have a border ?

**Comment by eric612** [comment]
I also see the interpolation method of resize use "INTER_CUBIC". This interpolation method may cost computing time

**Comment by eric612** [comment]
Okay ... , it not a good news , is it the same problems with original darknet model ?

**Comment by eric612** [comment]
I think I got a mistake of preprocessing , the vector mean_values = {0.5,0.5,0.5} may need change to {1.0,1.0,1.0}

**Comment by VigorPoppy** [comment]
@eric612 In your training prototxt, the mean_value is set to 127.5 and normalized valued is 0.007843. So in demo.sh I set the mean value to 0.5 and normalized value to 0.007843. What do you mean the change of {1.0, 1.0, 1.0}?

**Comment by eric612** [comment]
This mistake was from me , but it is out of topic , I will update my project soon

**Comment by eric612** [comment]
@VigorPoppy 

1. I put letter box resize on example\yolo\detect.cpp , just set resize mode =1 , you can compare result both project
2. Or you can retrain models with resize mode WARP , I recommend this

**Comment by lewes6369** [comment]
Hi,@VigorPoppy have you solved it? I checked the prototxts one more time.In caffe,there are some  DepthwiseConvolution layers which are Convolution layers in your tensorRT prototxt. They are different behaviors. It should affect the acc result.

**Comment by shiva13425** [comment]
@VigorPoppy Am trying to use trt.prototxt, yoloconfig.h and caffemodel you shared above to create trt engine. But am getting the below error,

ERROR: conv1/dw:  group count must divide input channel count
runYolov3: helpers.cpp:56: nvinfer1::DimsCHW nvinfer1::getCHW(const nvinfer1::Dims&): Assertion `d.nbDims >= 3' failed.
Aborted (core dumped)

Kindly share your comments
Note: its running in TensorRT 4

**Comment by biyuehuang** [comment]
> Hi,@VigorPoppy ,make sure your prototxt is the same name written in PluginFactory.h , name as "layer86-upsample ,layer98-upsample"

where is PluginFactory.h?

**Comment by JingzheLyp** [comment]
@shiva13425 Hi, have you solved the problem, ERROR: conv1/dw: group count must divide input channel count. I met the same error When I use conv layer with group=8. I can run caffe model correctly, but I can't convert the caffe model to TensorRT, when converting, the error occured.
